import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../components/Home/Home.module.scss'
import {BrowserRouter, Routes, Route} from "react-router-dom";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BrowserRouter>
        <Routes>
          <Route path={'/'} element={<DefaultPage />}>
            <Route index element={<Inicio />} />
            <Route path={'cardapio'} element={<Cardapio />} />
            <Route path={'sobre'} element={<Sobre />} />
            <Route path={'admin/:user'} element={<Admin />} />
          </Route>
        </Routes>
      </BrowserRouter>
    </div>
  )
}

export default Home
